package scoreboard
import("errors";"fmt";"math";"reflect";"sync";"testing")
func opts()Options{return Options{MaxMembers:16,MaxNameBytes:16}};func board(t *testing.T)*Board{t.Helper();b,e:=New(opts());if e!=nil{t.Fatal(e)};return b};func up(m string,s int64)Op{return Op{Kind:Upsert,Member:m,Score:s}};func inc(m string,d int64)Op{return Op{Kind:Increment,Member:m,Delta:d}};func del(m string)Op{return Op{Kind:Delete,Member:m}}
func TestOptionsAndValidationBeforeState(t *testing.T){if _,e:=New(Options{});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};b:=board(t);_,_=b.Apply(Batch{Ops:[]Op{up("a",1)}});before:=b.Snapshot();_,e:=b.Apply(Batch{Ops:[]Op{del("missing"),{Kind:Increment,Member:"bad?",Delta:1}}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,b.Snapshot()){t.Fatalf("e=%v",e)}}
func TestSequentialRevisionAndChanged(t *testing.T){b:=board(t);x,e:=b.Apply(Batch{Ops:[]Op{up("b",2),up("a",2),inc("a",3),del("b"),up("b",5)}});if e!=nil||x.Revision!=4||x.Generation!=1{t.Fatalf("x=%+v e=%v",x,e)};if len(x.Changed)!=2||x.Changed[0].Member!="a"||x.Changed[1].Member!="b"||x.Changed[0].Revision!=3||x.Changed[1].Revision!=4{t.Fatalf("changed=%+v",x.Changed)};s:=b.Snapshot();if s.NextRevision!=5{t.Fatalf("s=%+v",s)}}
func TestRollbackNotFoundOverflowCapacity(t *testing.T){b:=board(t);_,_=b.Apply(Batch{Ops:[]Op{up("a",math.MaxInt64)}});before:=b.Snapshot();_,e:=b.Apply(Batch{Ops:[]Op{inc("a",1)}});if !errors.Is(e,ErrOverflow)||!reflect.DeepEqual(before,b.Snapshot()){t.Fatal(e)};_,e=b.Apply(Batch{Ops:[]Op{del("missing")}});if !errors.Is(e,ErrNotFound){t.Fatal(e)};small,_:=New(Options{MaxMembers:1,MaxNameBytes:8});_,e=small.Apply(Batch{Ops:[]Op{up("a",1),up("b",2)}});if !errors.Is(e,ErrCapacity)||len(small.Snapshot().Entries)!=0{t.Fatal(e)};_,e=small.Apply(Batch{Ops:[]Op{up("a",1),del("a"),up("b",2)}});if e!=nil{t.Fatal(e)}}
func TestRangeOrderingCursorAndValidation(t *testing.T){b:=board(t);_,_=b.Apply(Batch{Ops:[]Op{up("c",9),up("a",5),up("b",5),up("d",1)}});x,e:=b.Range(1,9,Cursor{},3);if e!=nil||len(x)!=3||x[0].Member!="c"||x[1].Member!="a"||x[2].Member!="b"{t.Fatalf("x=%+v e=%v",x,e)};x,e=b.Range(1,9,Cursor{Set:true,Score:5,Member:"a0"},10);if e!=nil||len(x)!=2||x[0].Member!="b"||x[1].Member!="d"{t.Fatalf("x=%+v e=%v",x,e)};if _,e=b.Range(9,1,Cursor{},1);!errors.Is(e,ErrInvalidInput){t.Fatal(e)};if _,e=b.Range(1,9,Cursor{Set:true,Member:"bad?"},1);!errors.Is(e,ErrInvalidInput){t.Fatal(e)}}
func TestGetAndEmptyBatch(t *testing.T){b:=board(t);x,e:=b.Apply(Batch{});if e!=nil||x.Generation!=0||x.Revision!=0{t.Fatalf("x=%+v e=%v",x,e)};if _,ok,e:=b.Get("x");e!=nil||ok{t.Fatalf("ok=%v e=%v",ok,e)};if _,_,e:=b.Get("bad?");!errors.Is(e,ErrInvalidInput){t.Fatal(e)}}
func TestConcurrentUpdates(t *testing.T){b,_:=New(Options{MaxMembers:128,MaxNameBytes:16});var wg sync.WaitGroup;for i:=0;i<64;i++{i:=i;wg.Add(1);go func(){defer wg.Done();m:=fmt.Sprintf("m-%02d",i);_,_=b.Apply(Batch{Ops:[]Op{up(m,int64(i))}});_,_,_=b.Get(m);_=b.Snapshot()}()};wg.Wait();s:=b.Snapshot();if len(s.Entries)!=64||s.NextRevision!=65{t.Fatalf("s=%+v",s)}}
