package bimap
import("errors";"fmt";"reflect";"sync";"testing")
func opts()Options{return Options{MaxPairs:16,MaxNameBytes:16}};func reg(t *testing.T)*Registry{t.Helper();r,e:=New(opts());if e!=nil{t.Fatal(e)};return r};func bind(l,r string)Op{return Op{Kind:Bind,Left:l,Right:r}};func unbind(l,r string)Op{return Op{Kind:Unbind,Left:l,Right:r}}
func TestValidationBeforeState(t *testing.T){if _,e:=New(Options{});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{bind("a","1")}});before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{unbind("a","1"),bind("bad?","2")}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)}}
func TestConflictsAndMismatch(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{bind("a","1"),bind("b","2")}});for _,o:=range []Op{bind("a","3"),bind("c","2")}{if _,e:=r.Apply(Batch{Ops:[]Op{o}});!errors.Is(e,ErrConflict){t.Fatal(e)}};if _,e:=r.Apply(Batch{Ops:[]Op{unbind("a","2")}});!errors.Is(e,ErrMismatch){t.Fatal(e)};if _,e:=r.Apply(Batch{Ops:[]Op{unbind("x","9")}});!errors.Is(e,ErrNotFound){t.Fatal(e)}}
func TestReuseAndRevision(t *testing.T){r:=reg(t);x,_:=r.Apply(Batch{Ops:[]Op{bind("a","1"),bind("b","2")}});x2,e:=r.Apply(Batch{Ops:[]Op{unbind("a","1"),bind("a","3"),unbind("b","2"),bind("c","2")}});if e!=nil||x2.Revision!=x.Revision+2{t.Fatalf("x2=%+v e=%v",x2,e)};p,ok,_:=r.LookupRight("3");if !ok||p.Left!="a"{t.Fatalf("p=%+v",p)}}
func TestRollbackAndCapacity(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{bind("a","1")}});before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{unbind("a","1"),unbind("missing","x")}});if !errors.Is(e,ErrNotFound)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)};small,_:=New(Options{MaxPairs:1,MaxNameBytes:8});_,e=small.Apply(Batch{Ops:[]Op{bind("a","1"),bind("b","2")}});if !errors.Is(e,ErrCapacity){t.Fatal(e)}}
func TestListPaging(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{bind("c","3"),bind("a","1"),bind("b","2")}});x,e:=r.List("a",2);if e!=nil||len(x)!=2||x[0].Left!="b"||x[1].Left!="c"{t.Fatalf("x=%+v e=%v",x,e)};if _,e=r.List("bad?",1);!errors.Is(e,ErrInvalidInput){t.Fatal(e)}}
func TestConcurrentBinds(t *testing.T){r,_:=New(Options{MaxPairs:128,MaxNameBytes:16});var wg sync.WaitGroup;for i:=0;i<64;i++{i:=i;wg.Add(1);go func(){defer wg.Done();_,_=r.Apply(Batch{Ops:[]Op{bind(fmt.Sprintf("l-%02d",i),fmt.Sprintf("r-%02d",i))}});_=r.Snapshot()}()};wg.Wait();if len(r.Snapshot().Pairs)!=64{t.Fatal(r.Snapshot())}}
