package breaker
import("errors";"math";"reflect";"sync";"testing")
func options()Options{return Options{MaxServices:4,MaxNameBytes:16}};func policies()[]Policy{return []Policy{{Name:"api",FailureThreshold:2,RecoveryThreshold:2,OpenFor:5},{Name:"db",FailureThreshold:1,RecoveryThreshold:1,OpenFor:3}}};func reg(t *testing.T)*Registry{t.Helper();r,e:=New(options(),policies());if e!=nil{t.Fatal(e)};return r};func ev(s string,ok bool)Event{return Event{Service:s,Success:ok}}
func TestNewAndValidationBeforeState(t *testing.T){if _,e:=New(Options{},nil);!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};if _,e:=New(options(),[]Policy{{Name:"x",FailureThreshold:1,RecoveryThreshold:1,OpenFor:1},{Name:"x",FailureThreshold:1,RecoveryThreshold:1,OpenFor:1}});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};r:=reg(t);_,_=r.Record(Batch{Now:1,Events:[]Event{ev("db",false)}});before:=r.Snapshot();_,e:=r.Record(Batch{Now:5,Events:[]Event{ev("db",true),ev("bad?",true)}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v",e)}}
func TestClosedOpenHalfOpenClosed(t *testing.T){r:=reg(t);x,e:=r.Record(Batch{Now:1,Events:[]Event{ev("api",false),ev("api",false)}});if e!=nil||!reflect.DeepEqual(x.Changed,[]string{"api"}){t.Fatalf("x=%+v e=%v",x,e)};ok,s,e:=r.Allow("api",5);if e!=nil||ok||s.Mode!=Open{t.Fatalf("ok=%v s=%+v e=%v",ok,s,e)};ok,s,e=r.Allow("api",6);if e!=nil||!ok||s.Mode!=HalfOpen{t.Fatalf("ok=%v s=%+v e=%v",ok,s,e)};x,e=r.Record(Batch{Now:6,Events:[]Event{ev("api",true),ev("api",true)}});if e!=nil||r.Snapshot().Services[0].Mode!=Closed{t.Fatalf("x=%+v e=%v",x,e)}}
func TestRecordWhileOpenRollback(t *testing.T){r:=reg(t);_,_=r.Record(Batch{Now:1,Events:[]Event{ev("db",false)}});before:=r.Snapshot();_,e:=r.Record(Batch{Now:2,Events:[]Event{ev("api",false),ev("db",true)}});if !errors.Is(e,ErrOpen)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v",e)}}
func TestHalfOpenFailureAndSaturation(t *testing.T){r,_:=New(options(),[]Policy{{Name:"x",FailureThreshold:1,RecoveryThreshold:1,OpenFor:10}});_,_=r.Record(Batch{Now:math.MaxInt64-5,Events:[]Event{ev("x",false)}});s:=r.Snapshot().Services[0];if s.Mode!=Open||s.OpenUntil!=math.MaxInt64{t.Fatalf("s=%+v",s)};_,e:=r.Sweep(math.MaxInt64);if e!=nil{t.Fatal(e)};_,e=r.Record(Batch{Now:math.MaxInt64,Events:[]Event{ev("x",false)}});if e!=nil||r.Snapshot().Services[0].Mode!=Open{t.Fatalf("e=%v",e)}}
func TestSweepOrderTimeAndSnapshot(t *testing.T){r:=reg(t);_,_=r.Record(Batch{Now:1,Events:[]Event{ev("db",false),ev("api",false),ev("api",false)}});changed,e:=r.Sweep(6);if e!=nil||!reflect.DeepEqual(changed,[]string{"api","db"}){t.Fatalf("changed=%v e=%v",changed,e)};before:=r.Snapshot();_,e=r.Sweep(5);if !errors.Is(e,ErrTime)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)}}
func TestConcurrentAccess(t *testing.T){r:=reg(t);var wg sync.WaitGroup;for i:=0;i<32;i++{wg.Add(1);go func(){defer wg.Done();_,_,_=r.Allow("api",1);_,_=r.Record(Batch{Now:1,Events:[]Event{ev("api",true)} });_=r.Snapshot()}()};wg.Wait();s:=r.Snapshot();if s.Services[0].Mode!=Closed||s.Now!=1{t.Fatalf("s=%+v",s)}}
