package allocator
import("errors";"fmt";"math";"reflect";"sync";"testing")
func opts()Options{return Options{Size:64,MaxAllocations:16,MaxNameBytes:16}};func alloc(t *testing.T)*Allocator{t.Helper();a,e:=New(opts());if e!=nil{t.Fatal(e)};return a};func reserve(n string,s,l uint64)Op{return Op{Kind:Reserve,Name:n,Start:s,Length:l}};func allocate(n string,l,align uint64)Op{return Op{Kind:Allocate,Name:n,Length:l,Alignment:align}};func free(n string)Op{return Op{Kind:Free,Name:n}}
func TestOptionsAndValidationBeforeState(t *testing.T){if _,e:=New(Options{});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};a:=alloc(t);_,_=a.Apply(Batch{Ops:[]Op{reserve("a",0,4)}});before:=a.Snapshot();_,e:=a.Apply(Batch{Ops:[]Op{free("a"),{Kind:Allocate,Name:"bad?",Length:1,Alignment:1}}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,a.Snapshot()){t.Fatalf("e=%v",e)};_,e=a.Apply(Batch{Ops:[]Op{reserve("x",math.MaxUint64,2)}});if !errors.Is(e,ErrInvalidInput){t.Fatal(e)}}
func TestLowestAlignedAndFragmentation(t *testing.T){a:=alloc(t);x,e:=a.Apply(Batch{Ops:[]Op{reserve("left",0,3),reserve("mid",8,4),allocate("x",4,4),allocate("y",2,8)}});if e!=nil||x.Revision!=4{t.Fatalf("x=%+v e=%v",x,e)};sx,_,_:=a.Lookup("x");sy,_,_:=a.Lookup("y");if sx.Start!=4||sy.Start!=16{t.Fatalf("x=%+v y=%+v",sx,sy)};start,ok,e:=a.Find(3,2);if e!=nil||!ok||start!=12{t.Fatalf("start=%d ok=%v e=%v",start,ok,e)}}
func TestConflictNoSpaceAndRollback(t *testing.T){a,_:=New(Options{Size:8,MaxAllocations:4,MaxNameBytes:8});_,_=a.Apply(Batch{Ops:[]Op{reserve("a",0,4)}});before:=a.Snapshot();_,e:=a.Apply(Batch{Ops:[]Op{reserve("b",3,2)}});if !errors.Is(e,ErrConflict)||!reflect.DeepEqual(before,a.Snapshot()){t.Fatal(e)};_,e=a.Apply(Batch{Ops:[]Op{allocate("b",5,1)}});if !errors.Is(e,ErrNoSpace){t.Fatal(e)};_,e=a.Apply(Batch{Ops:[]Op{free("missing")}});if !errors.Is(e,ErrNotFound){t.Fatal(e)}}
func TestReleaseReuseAndRevision(t *testing.T){a:=alloc(t);_,_=a.Apply(Batch{Ops:[]Op{reserve("a",0,8),reserve("b",8,8)}});x,e:=a.Apply(Batch{Ops:[]Op{free("a"),allocate("a",4,4),free("b"),allocate("c",8,8)}});if e!=nil||x.Revision!=4{t.Fatalf("x=%+v e=%v",x,e)};aa,_,_:=a.Lookup("a");c,_,_:=a.Lookup("c");if aa.Start!=0||c.Start!=8||aa.Revision!=3||c.Revision!=4{t.Fatalf("a=%+v c=%+v",aa,c)}}
func TestFinalCapacityAndOrder(t *testing.T){a,_:=New(Options{Size:16,MaxAllocations:1,MaxNameBytes:8});_,e:=a.Apply(Batch{Ops:[]Op{reserve("a",0,1),reserve("b",2,1)}});if !errors.Is(e,ErrCapacity)||len(a.Snapshot().Allocations)!=0{t.Fatal(e)};_,e=a.Apply(Batch{Ops:[]Op{reserve("a",8,1),free("a"),reserve("b",4,1)}});if e!=nil{t.Fatal(e)}}
func TestConcurrentAllocations(t *testing.T){a,_:=New(Options{Size:1024,MaxAllocations:128,MaxNameBytes:16});var wg sync.WaitGroup;for i:=0;i<64;i++{i:=i;wg.Add(1);go func(){defer wg.Done();_,_=a.Apply(Batch{Ops:[]Op{allocate(fmt.Sprintf("a-%02d",i),1,1)}});_=a.Snapshot()}()};wg.Wait();s:=a.Snapshot();if len(s.Allocations)!=64||s.NextRevision!=65{t.Fatalf("s=%+v",s)};for i,x:=range s.Allocations{if x.Start!=uint64(i){t.Fatalf("i=%d x=%+v",i,x)}}}
