package ledger
import("errors";"fmt";"math";"reflect";"sync";"testing")
func opts()Options{return Options{MaxAccounts:16,MaxNameBytes:16}};func led(t *testing.T)*Ledger{t.Helper();l,e:=New(opts());if e!=nil{t.Fatal(e)};return l};func op(k OpKind,a,b string,n int64)Op{return Op{Kind:k,Account:a,Other:b,Amount:n}}
func TestValidationBeforeState(t *testing.T){if _,e:=New(Options{});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};l:=led(t);_,_=l.Apply(Batch{Ops:[]Op{op(Open,"a","",1)}});before:=l.Snapshot();_,e:=l.Apply(Batch{Ops:[]Op{op(Debit,"a","",1),op(Credit,"bad?","",1)}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,l.Snapshot()){t.Fatalf("e=%v",e)}}
func TestTransferRevisionAndSequential(t *testing.T){l:=led(t);x,e:=l.Apply(Batch{Ops:[]Op{op(Open,"a","",10),op(Open,"b","",0),op(Transfer,"a","b",4),op(Debit,"b","",1)}});if e!=nil||x.Revision!=4{t.Fatalf("x=%+v e=%v",x,e)};a,_,_:=l.Get("a");b,_,_:=l.Get("b");if a.Balance!=6||a.Revision!=3||b.Balance!=3||b.Revision!=4{t.Fatalf("a=%+v b=%+v",a,b)}}
func TestRollbackErrors(t *testing.T){l:=led(t);_,_=l.Apply(Batch{Ops:[]Op{op(Open,"a","",1)}});for _,q:=range []struct{o Op;want error}{{op(Open,"a","",0),ErrConflict},{op(Debit,"a","",2),ErrFunds},{op(Close,"a","",0),ErrBalance},{op(Credit,"missing","",1),ErrNotFound}}{before:=l.Snapshot();_,e:=l.Apply(Batch{Ops:[]Op{q.o}});if !errors.Is(e,q.want)||!reflect.DeepEqual(before,l.Snapshot()){t.Fatalf("e=%v",e)}}}
func TestOverflowRollback(t *testing.T){l:=led(t);_,_=l.Apply(Batch{Ops:[]Op{op(Open,"a","",math.MaxInt64)}});before:=l.Snapshot();_,e:=l.Apply(Batch{Ops:[]Op{op(Credit,"a","",1)}});if !errors.Is(e,ErrOverflow)||!reflect.DeepEqual(before,l.Snapshot()){t.Fatal(e)}}
func TestCloseReopenFinalCapacity(t *testing.T){l,_:=New(Options{MaxAccounts:1,MaxNameBytes:8});_,e:=l.Apply(Batch{Ops:[]Op{op(Open,"a","",0),op(Open,"b","",0)}});if !errors.Is(e,ErrCapacity){t.Fatal(e)};x,e:=l.Apply(Batch{Ops:[]Op{op(Open,"a","",0),op(Close,"a","",0),op(Open,"b","",2)}});if e!=nil||x.Revision!=3||len(l.Snapshot().Accounts)!=1{t.Fatalf("x=%+v e=%v",x,e)}}
func TestConcurrentCredits(t *testing.T){l:=led(t);_,_=l.Apply(Batch{Ops:[]Op{op(Open,"a","",0)}});var wg sync.WaitGroup;for i:=0;i<64;i++{wg.Add(1);go func(){defer wg.Done();_,_=l.Apply(Batch{Ops:[]Op{op(Credit,"a","",1)}});_=l.Snapshot()}()};wg.Wait();a,_,_:=l.Get("a");if a.Balance!=64{t.Fatalf("a=%+v %s",a,fmt.Sprint(l.Snapshot()))}}
