package barrier
import("errors";"fmt";"reflect";"sync";"testing")
func options()Options{return Options{MaxBarriers:4,MaxPending:16,MaxNameBytes:16}}
func reg(t *testing.T)*Registry{t.Helper();r,e:=New(options(),[]Config{{Name:"build",Parties:2},{Name:"deploy",Parties:3}});if e!=nil{t.Fatal(e)};return r}
func arr(b,p string)Op{return Op{Kind:Arrive,Barrier:b,Participant:p}}
func cancel(b,p string)Op{return Op{Kind:Cancel,Barrier:b,Participant:p}}
func TestNewAndValidationOrder(t *testing.T){if _,e:=New(Options{},nil);!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};if _,e:=New(options(),[]Config{{Name:"x",Parties:1},{Name:"x",Parties:2}});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{arr("build","a")}});before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{cancel("build","missing"),arr("bad?","x")}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v",e)}}
func TestCompletionAndSameBatchNextGeneration(t *testing.T){r:=reg(t);x,e:=r.Apply(Batch{Ops:[]Op{arr("build","b"),arr("build","a"),arr("build","a")}});if e!=nil||len(x.Completions)!=1{t.Fatalf("x=%+v e=%v",x,e)};c:=x.Completions[0];if c.Generation!=1||!reflect.DeepEqual(c.Participants,[]string{"a","b"}){t.Fatalf("c=%+v",c)};s:=r.Snapshot();if s.Barriers[0].Generation!=2||!reflect.DeepEqual(s.Barriers[0].Pending,[]string{"a"}){t.Fatalf("s=%+v",s)}}
func TestCancelConflictAndRollback(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{arr("build","a")}});before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{cancel("build","a"),cancel("build","a")}});if !errors.Is(e,ErrNotFound)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v",e)};_,e=r.Apply(Batch{Ops:[]Op{arr("build","a")}});if !errors.Is(e,ErrConflict){t.Fatal(e)}}
func TestUnknownBarrierAndFinalCapacity(t *testing.T){r:=reg(t);before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{arr("unknown","a")}});if !errors.Is(e,ErrNotFound)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)};small,_:=New(Options{MaxBarriers:2,MaxPending:1,MaxNameBytes:8},[]Config{{Name:"a",Parties:3},{Name:"b",Parties:2}});_,e=small.Apply(Batch{Ops:[]Op{arr("a","x"),arr("b","y")}});if !errors.Is(e,ErrCapacity)||small.Snapshot().Pending!=0{t.Fatalf("e=%v s=%+v",e,small.Snapshot())}}
func TestFinalCapacityAllowsIntermediateCompletion(t *testing.T){r,_:=New(Options{MaxBarriers:1,MaxPending:1,MaxNameBytes:8},[]Config{{Name:"b",Parties:2}});x,e:=r.Apply(Batch{Ops:[]Op{arr("b","x"),arr("b","y"),arr("b","z")}});if e!=nil||len(x.Completions)!=1||r.Snapshot().Pending!=1{t.Fatalf("x=%+v e=%v s=%+v",x,e,r.Snapshot())}}
func TestSnapshotOrderAndIsolation(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{arr("deploy","z"),arr("deploy","a"),arr("build","q")}});s:=r.Snapshot();if s.Barriers[0].Name!="build"||!reflect.DeepEqual(s.Barriers[1].Pending,[]string{"a","z"}){t.Fatalf("s=%+v",s)};s.Barriers[1].Pending[0]="mutated";if r.Snapshot().Barriers[1].Pending[0]!="a"{t.Fatal("alias")}}
func TestConcurrentBatches(t *testing.T){r,_:=New(Options{MaxBarriers:1,MaxPending:128,MaxNameBytes:16},[]Config{{Name:"b",Parties:100}});var wg sync.WaitGroup;for i:=0;i<64;i++{i:=i;wg.Add(1);go func(){defer wg.Done();_,_=r.Apply(Batch{Ops:[]Op{arr("b",fmt.Sprintf("p-%02d",i))}});_=r.Snapshot()}()};wg.Wait();s:=r.Snapshot();if s.Pending!=64||s.Generation!=64{t.Fatalf("s=%+v",s)}}
