package prefixclaim
import("errors";"fmt";"reflect";"sync";"testing")
func opts()Options{return Options{MaxClaims:16,MaxPathBytes:32,MaxOwnerBytes:16}};func reg(t *testing.T)*Registry{t.Helper();r,e:=New(opts());if e!=nil{t.Fatal(e)};return r};func claim(p,o string)Op{return Op{Kind:Claim,Path:p,Owner:o}};func release(p,o string)Op{return Op{Kind:Release,Path:p,Owner:o}}
func TestValidationBeforeState(t *testing.T){if _,e:=New(Options{});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{claim("/a","o")}});before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{release("/a","o"),claim("/bad//x","o")}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v",e)}}
func TestPrefixBoundaries(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{claim("/a","o")}});for _,p:=range []string{"/a","/a/b"}{if _,e:=r.Apply(Batch{Ops:[]Op{claim(p,"x")}});!errors.Is(e,ErrConflict){t.Fatalf("p=%s e=%v",p,e)}};if _,e:=r.Apply(Batch{Ops:[]Op{claim("/ab","x")}});e!=nil{t.Fatal(e)};x,ok,e:=r.Lookup("/a/b/c");if e!=nil||!ok||x.Path!="/a"{t.Fatalf("x=%+v ok=%v e=%v",x,ok,e)}}
func TestReleaseOwnerRollbackRevision(t *testing.T){r:=reg(t);x,_:=r.Apply(Batch{Ops:[]Op{claim("/a","o")}});before:=r.Snapshot();_,e:=r.Apply(Batch{Ops:[]Op{release("/a","bad")}});if !errors.Is(e,ErrOwner)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)};x2,e:=r.Apply(Batch{Ops:[]Op{release("/a","o"),claim("/a/b","n")}});if e!=nil||x2.Revision!=x.Revision+1{t.Fatalf("x=%+v x2=%+v e=%v",x,x2,e)}}
func TestRootAndFinalCapacity(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{claim("/","root")}});if _,e:=r.Apply(Batch{Ops:[]Op{claim("/x","x")}});!errors.Is(e,ErrConflict){t.Fatal(e)};small,_:=New(Options{MaxClaims:1,MaxPathBytes:16,MaxOwnerBytes:8});_,e:=small.Apply(Batch{Ops:[]Op{claim("/a","o"),claim("/b","o")}});if !errors.Is(e,ErrCapacity)||len(small.Snapshot().Entries)!=0{t.Fatal(e)}}
func TestDescendantsPaging(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Ops:[]Op{claim("/a/b","o"),claim("/a/c","o"),claim("/ab","o")}});x,e:=r.Descendants("/a","",1);if e!=nil||len(x)!=1||x[0].Path!="/a/b"{t.Fatalf("x=%+v e=%v",x,e)};x,e=r.Descendants("/a","/a/b",10);if e!=nil||len(x)!=1||x[0].Path!="/a/c"{t.Fatalf("x=%+v e=%v",x,e)}}
func TestConcurrentClaims(t *testing.T){r,_:=New(Options{MaxClaims:128,MaxPathBytes:32,MaxOwnerBytes:8});var wg sync.WaitGroup;for i:=0;i<64;i++{i:=i;wg.Add(1);go func(){defer wg.Done();_,_=r.Apply(Batch{Ops:[]Op{claim(fmt.Sprintf("/p/%02d",i),"o")}});_=r.Snapshot()}()};wg.Wait();if len(r.Snapshot().Entries)!=64{t.Fatalf("s=%+v",r.Snapshot())}}
