package windowcounter
import("errors";"fmt";"math";"reflect";"sync";"testing")
func opts()Options{return Options{Window:10,MaxKeys:16,MaxEvents:64,MaxNameBytes:16}};func reg(t *testing.T)*Registry{t.Helper();r,e:=New(opts());if e!=nil{t.Fatal(e)};return r};func d(k string,n int64)Delta{return Delta{Key:k,Amount:n}}
func TestOptionsAndValidationBeforeState(t *testing.T){if _,e:=New(Options{});!errors.Is(e,ErrInvalidOptions){t.Fatal(e)};r:=reg(t);_,_=r.Apply(Batch{Now:1,Deltas:[]Delta{d("a",2)}});before:=r.Snapshot();_,e:=r.Apply(Batch{Now:20,Deltas:[]Delta{d("a",-1),d("bad?",1)}});if !errors.Is(e,ErrInvalidInput)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v",e)}}
func TestBoundaryGetAndSweep(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Now:2,Deltas:[]Delta{d("a",2)}});v,ok,e:=r.Get("a",11);if e!=nil||!ok||v!=2{t.Fatalf("v=%d ok=%v e=%v",v,ok,e)};v,ok,e=r.Get("a",12);if e!=nil||ok||v!=0{t.Fatalf("v=%d ok=%v e=%v",v,ok,e)};if r.Snapshot().Generation!=2{t.Fatalf("s=%+v",r.Snapshot())};n,e:=r.Sweep(20);if e!=nil||n!=0{t.Fatalf("n=%d e=%v",n,e)}}
func TestSequentialUnderflowRollback(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Now:1,Deltas:[]Delta{d("a",5)}});before:=r.Snapshot();_,e:=r.Apply(Batch{Now:12,Deltas:[]Delta{d("a",2),d("a",-3)}});if !errors.Is(e,ErrUnderflow)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatalf("e=%v s=%+v",e,r.Snapshot())};x,e:=r.Apply(Batch{Now:2,Deltas:[]Delta{d("a",-2),d("a",1)}});if e!=nil||x.Counts[0].Value!=4{t.Fatalf("x=%+v e=%v",x,e)}}
func TestOverflowAndTimeRollback(t *testing.T){r:=reg(t);_,_=r.Apply(Batch{Now:1,Deltas:[]Delta{d("a",math.MaxInt64)}});before:=r.Snapshot();_,e:=r.Apply(Batch{Now:2,Deltas:[]Delta{d("a",1)}});if !errors.Is(e,ErrOverflow)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)};_,e=r.Apply(Batch{Now:0});if !errors.Is(e,ErrTime){t.Fatal(e)}}
func TestFinalCapacityAndSortedCounts(t *testing.T){r,_:=New(Options{Window:5,MaxKeys:1,MaxEvents:2,MaxNameBytes:8});_,_=r.Apply(Batch{Now:1,Deltas:[]Delta{d("a",1),d("a",1)}});before:=r.Snapshot();_,e:=r.Apply(Batch{Now:2,Deltas:[]Delta{d("b",1)}});if !errors.Is(e,ErrCapacity)||!reflect.DeepEqual(before,r.Snapshot()){t.Fatal(e)};x,e:=r.Apply(Batch{Now:6,Deltas:[]Delta{d("b",2),d("b",-1)}});if e!=nil||x.ExpiredEvents!=2||len(x.Counts)!=1||x.Counts[0].Key!="b"{t.Fatalf("x=%+v e=%v",x,e)}}
func TestSnapshotAndConcurrency(t *testing.T){r,_:=New(Options{Window:20,MaxKeys:128,MaxEvents:256,MaxNameBytes:16});var wg sync.WaitGroup;for i:=0;i<64;i++{i:=i;wg.Add(1);go func(){defer wg.Done();k:=fmt.Sprintf("k-%02d",i);_,_=r.Apply(Batch{Now:1,Deltas:[]Delta{d(k,1)}});_,_,_=r.Get(k,1);_=r.Snapshot()}()};wg.Wait();s:=r.Snapshot();if len(s.Keys)!=64||s.Keys[0].Key!="k-00"||s.Events!=64{t.Fatalf("s=%+v",s)}}
